### ISSUE TITLE
[TwigBundle] Missing configuration reference

### ISSUE THREAD

**Issue by carsonbot-test** [carsonbot-playground/symfony#17]
I found that there are some configuration missing for the TwigBundle configuration reference page. This is a list of what is missing: 

```
- twig.globals.foo

```

Could someone please add these?

**Comment by OskarStark** [comment]
Really `foo`? 👀

**Comment by Nyholm** [comment]
Im looking into this.. Im not sure what to do. It comes from the example.. 

```yaml
# Default configuration for "TwigBundle"
twig:
    globals:

        # Examples:
        foo:                 '@bar'
        pi:                  3.14

```
